version: '3.8'
name: docker

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8080:80'
    networks:
      - tech-haven_network

networks:
  tech-haven_network:
    external: true
    name: docker_tech-haven_network
