version: '3.8'
name: docker

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8080:80'
    networks:
      docker_nginx_network:
        ipv4_address: 172.22.0.14

networks:
  docker_nginx_network:
    external: true
